package personal.vramachandran.crowdflow;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vramachandran' at '2/2/15 3:58 PM' with Gradle 2.2.1
 *
 * @author vramachandran, @date 2/2/15 3:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
