package personal.vramachandran.crowdflow.test;

import org.junit.Test;

import personal.vramachandran.crowdflow.Library;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'vramachandran' at '2/2/15 3:58 PM' with Gradle 2.2.1
 *
 * @author vramachandran, @date 2/2/15 3:58 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
